import {
  Activity,
  DollarSign,
  Award,
  TrendingUp,
  Code,
  Briefcase,
} from "lucide-react";
import { Achievement } from "../types";

export const achievementsData: Achievement[] = [
  // Completed Achievements
  {
    id: 1,
    title: "Sub-5 Minute Kilometer",
    description: "Achieved personal best pace of 4:58/km",
    category: "fitness",
    date: "2024-01-15",
    metric: "4:58 /km",
    icon: Activity,
    completed: true,
    completedDate: "2024-01-15",
    type: "achievement",
  },
  {
    id: 2,
    title: "Emergency Fund Complete",
    description: "Built 6-month emergency fund",
    category: "finances",
    date: "2024-01-12",
    metric: "$15,600",
    icon: DollarSign,
    completed: true,
    completedDate: "2024-01-12",
    type: "achievement",
  },
  {
    id: 3,
    title: "AWS Certification",
    description: "Earned AWS Solutions Architect certification",
    category: "learning",
    date: "2024-01-10",
    metric: "Certified",
    icon: Award,
    completed: true,
    completedDate: "2024-01-10",
    type: "achievement",
  },
  {
    id: 4,
    title: "Salary Increase",
    description: "Negotiated 18% salary increase",
    category: "career",
    date: "2024-01-08",
    metric: "+$936/month",
    icon: TrendingUp,
    completed: true,
    completedDate: "2024-01-08",
    type: "achievement",
  },
  // Goal-type Achievements (In Progress)
  {
    id: 5,
    title: "Run Half Marathon",
    description: "Complete a half marathon under 1 hour 45 minutes",
    category: "fitness",
    date: "2024-03-15",
    metric: "Sub 1:45:00",
    icon: Activity,
    completed: false,
    type: "goal",
    progress: 75,
    target: "Sub 1:45:00",
    deadline: "March 2024",
    current: "Current best: 1:52:30",
  },
  {
    id: 6,
    title: "Reach $50K Net Worth",
    description: "Build net worth to $50,000 through savings and investments",
    category: "finances",
    date: "2024-02-28",
    metric: "$50,000",
    icon: DollarSign,
    completed: false,
    type: "goal",
    progress: 90,
    target: "$50,000",
    deadline: "February 2024",
    current: "Current: $45,250",
  },
  {
    id: 7,
    title: "Complete React Course",
    description: "Master advanced React patterns and TypeScript",
    category: "learning",
    date: "2024-01-31",
    metric: "100% completion",
    icon: Code,
    completed: false,
    type: "goal",
    progress: 60,
    target: "100% completion",
    deadline: "January 2024",
    current: "12/20 modules done",
  },
  {
    id: 8,
    title: "Lead Team Project",
    description: "Lead a major project to demonstrate leadership skills",
    category: "career",
    date: "2024-04-30",
    metric: "Successfully deliver",
    icon: Briefcase,
    completed: false,
    type: "goal",
    progress: 40,
    target: "Successfully deliver",
    deadline: "April 2024",
    current: "Planning phase",
  },
  // Future Achievements/Goals
  {
    id: 9,
    title: "Run 10K Under 50 Minutes",
    description: "Complete a 10K run in under 50 minutes",
    category: "fitness",
    date: "2024-01-20",
    metric: "Target: <50:00",
    icon: Activity,
    completed: false,
    type: "achievement",
  },
  {
    id: 10,
    title: "Save $60K Net Worth",
    description: "Reach $60,000 in total net worth",
    category: "finances",
    date: "2024-06-01",
    metric: "Target: $60,000",
    icon: DollarSign,
    completed: false,
    type: "achievement",
  },
];
