import { Activity, DollarSign, Code, Briefcase } from "lucide-react";

export const categoriesData = [
    {
      id: "fitness",
      name: "Health & Fitness",
      icon: Activity,
      color: "bg-green-500",
      stats: {
        runningPace: "5:42 /km",
        bestPace: "4:58 /km",
        currentWeight: "75.2 kg",
        bodyFat: "18.5%",
        leanMass: "61.3 kg",
        fatMass: "13.9 kg",
        totalDistance: "287.5 km",
        thisWeek: "12.5 km",
        longestRun: "18.2 km",
        targetWeight: "73 kg",
        targetBodyFat: "15%",
      },
    },
    {
      id: "finances",
      name: "Financial Health",
      icon: DollarSign,
      color: "bg-emerald-500",
      stats: {
        netWorth: "$45,250",
        monthlyIncome: "$5,200",
        savingsRate: "28%",
        investmentGrowth: "+12.4%",
        emergencyFund: "6 months",
        monthlyExpenses: "$3,744",
        savingsAmount: "$1,456",
        investmentValue: "$28,500",
        debtAmount: "$0",
        targetNetWorth: "$50,000",
      },
    },
    {
      id: "learning",
      name: "Education & Skills",
      icon: Code,
      color: "bg-blue-500",
      stats: {
        degreeProgress: "75%",
        yearsRemaining: "1.5 years",
        skillsLearned: "8",
        coursesCompleted: "12",
        currentGPA: "3.7",
        university: "State University",
        major: "Computer Science",
        expectedGraduation: "May 2025",
        creditsCompleted: "90",
        totalCredits: "120",
        currentCourses: "3",
      },
    },
    {
      id: "career",
      name: "Career & Work",
      icon: Briefcase,
      color: "bg-purple-500",
      stats: {
        currentRole: "Mid-Level Developer",
        company: "Tech Solutions Inc.",
        yearsExperience: "3.2 years",
        currentSalary: "$85,000",
        location: "San Francisco, CA",
        startDate: "March 2021",
        teamSize: "5 people",
        projectsCompleted: "23",
        targetRole: "Senior Developer",
        targetSalary: "$110,000",
        targetDate: "June 2024",
      },
    },
  ]
